version: 0.0.{build}-ci
image: Visual Studio 2017
configuration: Release
init:
- ps: >-
    if ($env:appveyor_repo_tag -eq 'true') {
        $tag = $env:appveyor_repo_tag_name
        Update-AppveyorBuild -Version "$tag"
    }

dotnet_csproj:
  patch: true
  file: src\Fleck\Fleck.csproj
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build_script:
- ps: >-
    cd .\src\

    dotnet build -c Release

    dotnet pack Fleck -c Release
artifacts:
- path: .\src\Fleck\bin\Release\*.nupkg

nuget:
  project_feed: true
  disable_publish_on_pr: true

notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
